inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2 # adjust this to match your Ruby version

Rails:
  Enabled: true

# custom configuration
Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - bin

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/initializers/*"
    - "lib/tasks/*"

Metrics/MethodLength:
  Exclude:
    - "db/**/*"

Rails/BulkChangeTable:
  Enabled: false
