services:
  db:
    image: postgres
    container_name: backstage-db
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '5432:5432'

  redis:
    container_name: backstage-redis
    image: "redis:alpine"
    ports:
      - '6379:6379'

  app:
    container_name: backstage-api
    tty: true
    stdin_open: true
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - gems:/box/gems
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
      - box
      - redis
    links:
      - db
      - box
      - redis

  box:
    container_name: backstage-bundle-box
    image: busybox
    volumes:
      - gems:/box/gems

  sidekiq:
    container_name: backstage-sidekiq
    tty: true
    stdin_open: true
    build:
      context: .
      target: development
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - gems:/box/gems
    env_file:
      - .env
    depends_on:
      - box
      - redis
    links:
      - box
      - redis

volumes:
  gems:
