syncronize_issues:
  name: issues_job, # must be uniq!
  cron: "every 1 hour"
  class: "IssuesJob"
  queue: default

syncronize_time_entries:
  name: time_entries_job, # must be uniq!
  cron: "every 5 minutes"
  class: "TimeEntriesJob"
  queue: default
