name: Continuous Integration

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST: localhost
  ACTIVE_RECORD_ENCRYPTION_PRIVATE_KEY: test
  ACTIVE_RECORD_KEY_DERIVATION_SALT: test
  VALID_USER_DOMAIN: codelitt.com

on:
  workflow_dispatch:
  push:
    branches: ["*/*"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Database setup and migration
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rspec
